//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5477
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://TNX.CollectService/", ClrNamespace = "tnx.collectservice")]

namespace tnx.collectservice
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "AirTicketCollectData", Namespace = "http://TNX.CollectService/")]
    public partial class AirTicketCollectData : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private int AirTicketCollectDataIDField;

        private string CollectFlagField;

        private string DepartCityField;

        private string ArriveCityField;

        private string DepartAirportField;

        private string ArriveAirportField;

        private System.DateTime DepartDateField;

        private string CarrierField;

        private string FlightNOField;

        private string ShareFlightNOField;

        private string ClassField;

        private decimal DiscountField;

        private int SeatingsField;

        private string ServiceField;

        private decimal ServicePriceField;

        private decimal FareField;

        private decimal CommissionRateField;

        private decimal CommissionField;

        private decimal SettlementPriceField;

        private bool ContainServiceField;

        private int PriceTypeField;

        private string PriceTypeNameField;

        private decimal FareCHDField;

        private decimal CommissionRateCHDField;

        private decimal CommissionCHDField;

        private decimal SettlementPriceCHDField;

        private decimal FareINFField;

        private decimal SettlementPriceINFField;

        private decimal FuelTaxField;

        private decimal AirportTaxField;

        private decimal FuelTaxCHDField;

        private decimal AirportTaxCHDField;

        private decimal FuelTaxINFField;

        private string RefundChangeRateField;

        private string RefundField;

        private string ChangeField;

        private string DepartTimeField;

        private string ArriveTimeField;

        private string AircarftField;

        private bool MealField;

        private string StopsField;

        private decimal PunctualityField;

        private System.DateTime CreateTimeField;

        private int BatchField;

        private string SystemCodeField;

        private string SiteCodeField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public int AirTicketCollectDataID
        {
            get
            {
                return this.AirTicketCollectDataIDField;
            }
            set
            {
                this.AirTicketCollectDataIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string CollectFlag
        {
            get
            {
                return this.CollectFlagField;
            }
            set
            {
                this.CollectFlagField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false)]
        public string DepartCity
        {
            get
            {
                return this.DepartCityField;
            }
            set
            {
                this.DepartCityField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 3)]
        public string ArriveCity
        {
            get
            {
                return this.ArriveCityField;
            }
            set
            {
                this.ArriveCityField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 4)]
        public string DepartAirport
        {
            get
            {
                return this.DepartAirportField;
            }
            set
            {
                this.DepartAirportField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 5)]
        public string ArriveAirport
        {
            get
            {
                return this.ArriveAirportField;
            }
            set
            {
                this.ArriveAirportField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 6)]
        public System.DateTime DepartDate
        {
            get
            {
                return this.DepartDateField;
            }
            set
            {
                this.DepartDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 7)]
        public string Carrier
        {
            get
            {
                return this.CarrierField;
            }
            set
            {
                this.CarrierField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 8)]
        public string FlightNO
        {
            get
            {
                return this.FlightNOField;
            }
            set
            {
                this.FlightNOField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 9)]
        public string ShareFlightNO
        {
            get
            {
                return this.ShareFlightNOField;
            }
            set
            {
                this.ShareFlightNOField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 10)]
        public string Class
        {
            get
            {
                return this.ClassField;
            }
            set
            {
                this.ClassField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 11)]
        public decimal Discount
        {
            get
            {
                return this.DiscountField;
            }
            set
            {
                this.DiscountField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 12)]
        public int Seatings
        {
            get
            {
                return this.SeatingsField;
            }
            set
            {
                this.SeatingsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 13)]
        public string Service
        {
            get
            {
                return this.ServiceField;
            }
            set
            {
                this.ServiceField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 14)]
        public decimal ServicePrice
        {
            get
            {
                return this.ServicePriceField;
            }
            set
            {
                this.ServicePriceField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 15)]
        public decimal Fare
        {
            get
            {
                return this.FareField;
            }
            set
            {
                this.FareField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 16)]
        public decimal CommissionRate
        {
            get
            {
                return this.CommissionRateField;
            }
            set
            {
                this.CommissionRateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 17)]
        public decimal Commission
        {
            get
            {
                return this.CommissionField;
            }
            set
            {
                this.CommissionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 18)]
        public decimal SettlementPrice
        {
            get
            {
                return this.SettlementPriceField;
            }
            set
            {
                this.SettlementPriceField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 19)]
        public bool ContainService
        {
            get
            {
                return this.ContainServiceField;
            }
            set
            {
                this.ContainServiceField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 20)]
        public int PriceType
        {
            get
            {
                return this.PriceTypeField;
            }
            set
            {
                this.PriceTypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 21)]
        public string PriceTypeName
        {
            get
            {
                return this.PriceTypeNameField;
            }
            set
            {
                this.PriceTypeNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 22)]
        public decimal FareCHD
        {
            get
            {
                return this.FareCHDField;
            }
            set
            {
                this.FareCHDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 23)]
        public decimal CommissionRateCHD
        {
            get
            {
                return this.CommissionRateCHDField;
            }
            set
            {
                this.CommissionRateCHDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 24)]
        public decimal CommissionCHD
        {
            get
            {
                return this.CommissionCHDField;
            }
            set
            {
                this.CommissionCHDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 25)]
        public decimal SettlementPriceCHD
        {
            get
            {
                return this.SettlementPriceCHDField;
            }
            set
            {
                this.SettlementPriceCHDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 26)]
        public decimal FareINF
        {
            get
            {
                return this.FareINFField;
            }
            set
            {
                this.FareINFField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 27)]
        public decimal SettlementPriceINF
        {
            get
            {
                return this.SettlementPriceINFField;
            }
            set
            {
                this.SettlementPriceINFField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 28)]
        public decimal FuelTax
        {
            get
            {
                return this.FuelTaxField;
            }
            set
            {
                this.FuelTaxField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 29)]
        public decimal AirportTax
        {
            get
            {
                return this.AirportTaxField;
            }
            set
            {
                this.AirportTaxField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 30)]
        public decimal FuelTaxCHD
        {
            get
            {
                return this.FuelTaxCHDField;
            }
            set
            {
                this.FuelTaxCHDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 31)]
        public decimal AirportTaxCHD
        {
            get
            {
                return this.AirportTaxCHDField;
            }
            set
            {
                this.AirportTaxCHDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 32)]
        public decimal FuelTaxINF
        {
            get
            {
                return this.FuelTaxINFField;
            }
            set
            {
                this.FuelTaxINFField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 33)]
        public string RefundChangeRate
        {
            get
            {
                return this.RefundChangeRateField;
            }
            set
            {
                this.RefundChangeRateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 34)]
        public string Refund
        {
            get
            {
                return this.RefundField;
            }
            set
            {
                this.RefundField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 35)]
        public string Change
        {
            get
            {
                return this.ChangeField;
            }
            set
            {
                this.ChangeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 36)]
        public string DepartTime
        {
            get
            {
                return this.DepartTimeField;
            }
            set
            {
                this.DepartTimeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 37)]
        public string ArriveTime
        {
            get
            {
                return this.ArriveTimeField;
            }
            set
            {
                this.ArriveTimeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 38)]
        public string Aircarft
        {
            get
            {
                return this.AircarftField;
            }
            set
            {
                this.AircarftField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 39)]
        public bool Meal
        {
            get
            {
                return this.MealField;
            }
            set
            {
                this.MealField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 40)]
        public string Stops
        {
            get
            {
                return this.StopsField;
            }
            set
            {
                this.StopsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 41)]
        public decimal Punctuality
        {
            get
            {
                return this.PunctualityField;
            }
            set
            {
                this.PunctualityField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 42)]
        public System.DateTime CreateTime
        {
            get
            {
                return this.CreateTimeField;
            }
            set
            {
                this.CreateTimeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 43)]
        public int Batch
        {
            get
            {
                return this.BatchField;
            }
            set
            {
                this.BatchField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 44)]
        public string SystemCode
        {
            get
            {
                return this.SystemCodeField;
            }
            set
            {
                this.SystemCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 45)]
        public string SiteCode
        {
            get
            {
                return this.SiteCodeField;
            }
            set
            {
                this.SiteCodeField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace = "http://TNX.CollectService/", ConfigurationName = "ICollectService")]
public interface ICollectService
{

    // CODEGEN: 命名空间 http://TNX.CollectService/ 的元素名称 airTicketCollectData 以后生成的消息协定未标记为 nillable
    [System.ServiceModel.OperationContractAttribute(Action = "http://TNX.CollectService/ICollectService/SubmitAirTicketCollectData", ReplyAction = "http://TNX.CollectService/ICollectService/SubmitAirTicketCollectDataResponse")]
    SubmitAirTicketCollectDataResponse SubmitAirTicketCollectData(SubmitAirTicketCollectDataRequest request);

    [System.ServiceModel.OperationContractAttribute(Action = "http://TNX.CollectService/ICollectService/GetListDic", ReplyAction = "http://TNX.CollectService/ICollectService/GetListDicResponse")]
    System.Collections.Generic.Dictionary<string, string[]> GetListDic(string systemCode);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
public partial class SubmitAirTicketCollectDataRequest
{

    [System.ServiceModel.MessageBodyMemberAttribute(Name = "SubmitAirTicketCollectData", Namespace = "http://TNX.CollectService/", Order = 0)]
    public SubmitAirTicketCollectDataRequestBody Body;

    public SubmitAirTicketCollectDataRequest()
    {
    }

    public SubmitAirTicketCollectDataRequest(SubmitAirTicketCollectDataRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace = "http://TNX.CollectService/")]
public partial class SubmitAirTicketCollectDataRequestBody
{

    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
    public tnx.collectservice.AirTicketCollectData[] airTicketCollectData;

    public SubmitAirTicketCollectDataRequestBody()
    {
    }

    public SubmitAirTicketCollectDataRequestBody(tnx.collectservice.AirTicketCollectData[] airTicketCollectData)
    {
        this.airTicketCollectData = airTicketCollectData;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
public partial class SubmitAirTicketCollectDataResponse
{

    [System.ServiceModel.MessageBodyMemberAttribute(Name = "SubmitAirTicketCollectDataResponse", Namespace = "http://TNX.CollectService/", Order = 0)]
    public SubmitAirTicketCollectDataResponseBody Body;

    public SubmitAirTicketCollectDataResponse()
    {
    }

    public SubmitAirTicketCollectDataResponse(SubmitAirTicketCollectDataResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Runtime.Serialization.DataContractAttribute(Namespace = "http://TNX.CollectService/")]
public partial class SubmitAirTicketCollectDataResponseBody
{

    [System.Runtime.Serialization.DataMemberAttribute(Order = 0)]
    public bool SubmitAirTicketCollectDataResult;

    public SubmitAirTicketCollectDataResponseBody()
    {
    }

    public SubmitAirTicketCollectDataResponseBody(bool SubmitAirTicketCollectDataResult)
    {
        this.SubmitAirTicketCollectDataResult = SubmitAirTicketCollectDataResult;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface ICollectServiceChannel : ICollectService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class CollectServiceClient : System.ServiceModel.ClientBase<ICollectService>, ICollectService
{

    public CollectServiceClient()
    {
    }

    public CollectServiceClient(string endpointConfigurationName) :
        base(endpointConfigurationName)
    {
    }

    public CollectServiceClient(string endpointConfigurationName, string remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public CollectServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public CollectServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
        base(binding, remoteAddress)
    {
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    SubmitAirTicketCollectDataResponse ICollectService.SubmitAirTicketCollectData(SubmitAirTicketCollectDataRequest request)
    {
        return base.Channel.SubmitAirTicketCollectData(request);
    }

    public bool SubmitAirTicketCollectData(tnx.collectservice.AirTicketCollectData[] airTicketCollectData)
    {
        SubmitAirTicketCollectDataRequest inValue = new SubmitAirTicketCollectDataRequest();
        inValue.Body = new SubmitAirTicketCollectDataRequestBody();
        inValue.Body.airTicketCollectData = airTicketCollectData;
        SubmitAirTicketCollectDataResponse retVal = ((ICollectService)(this)).SubmitAirTicketCollectData(inValue);
        return retVal.Body.SubmitAirTicketCollectDataResult;
    }

    public System.Collections.Generic.Dictionary<string, string[]> GetListDic(string systemCode)
    {
        return base.Channel.GetListDic(systemCode);
    }
}
